#!/usr/bin/env python3
"""Build site/tracker/index.html from the template + data.json.

Inputs (all in this pipeline/ dir):
  template.dc.html     - the app (contains the `const DATA = /* __DATA_INJECT__ */{}/* __DATA_INJECT__ */;` marker)
  data.json            - the dashboard's values (regenerated by generate.py)
  artifact-shell.html  - stable inlined React + ReactDOM + support.js + the __DC_SRC__ slot (rarely changes)

Output:
  ../site/tracker/index.html  (Vercel serves this at /tracker)

The written page is HEAD (title/icons/link-preview tags, defined below) + shell + body.

The artifact carries the app body twice: as the escaped __DC_SRC__ payload AND as the
raw inline <x-dc> body that support.js actually renders. This build writes BOTH from the
current template+data (a stale inline body ships a broken page).

Usage:  python3 build.py
"""
import json, pathlib, re, struct

PIPE = pathlib.Path(__file__).parent
TEMPLATE = PIPE / "template.dc.html"
DATA_JSON = PIPE / "data.json"
SHELL = PIPE / "artifact-shell.html"
PALETTE_JSON = PIPE / "app-palette.json"
INTER_CSS = PIPE / "inter-latin.css"
SITE_DIR = PIPE.parent / "site"

DATA_MARKER = "/* __DATA_INJECT__ */{}/* __DATA_INJECT__ */"
VARIANT_MARKER = "/* __VARIANT_INJECT__ */{ name: 'web', routeBase: '/tracker' }/* __VARIANT_INJECT__ */"

# Document head. The shell starts straight at <script>, so without this the page ships no
# title, no icon, no charset and no link-preview tags. It lives here rather than in
# artifact-shell.html (which is regenerated wholesale) or the template's <helmet> block --
# helmet is appended by JS after boot, which browsers honour but crawlers and link unfurlers
# never see. HTML5 implies <head> for leading meta/title, so no wrapper tags are needed.
DESCRIPTION = (
    "Market updates and trends across entry-level and lateral attorney recruiting, updated "
    "every weekday. Now supporting both law firm and public interest recruiting insights."
)
SITE = "https://resources.joinflo.com"
# The public page is canonical for both builds: every /tracker/* path is served the same
# document by the vercel.json rewrite, and the in-app copy is that content again -- without
# this, crawlers would treat each deep link and the whole app variant as duplicates.
CANONICAL = f"{SITE}/tracker"

# One template, two builds. 'web' is the public marketing page; 'app' is the pared-back copy
# for users arriving from inside the Flo application. Never fork template.dc.html -- put
# differences behind VARIANT there, so both stay in step including on the daily refresh.
VARIANTS = (
    {
        "name": "web",
        "out": ("tracker", "index.html"),
        "route_base": "/tracker",
        "title": "Legal Recruiting Tracker | Flo Forward",
        "robots": None,
        "retheme": False,
        # Per-variant CSS, appended after the body so it wins over the runtime's own styles.
        "css": "",
    },
    {
        "name": "app",
        "out": ("app", "tracker", "index.html"),
        "route_base": "/app/tracker",
        "title": "Legal Recruiting Tracker",
        # Same content as the public page: keep it out of search, point search at that one.
        "robots": "noindex, nofollow",
        "retheme": True,          # apply app-palette.json + Inter to inline styles
        # Solid dark buttons -> Flo Kit action tokens. Anchored to `background:` so the same
        # hex used as text still resolves to the neutral ink via the palette.
        # Flo Kit type scale: H1 32/40, H2 28/36, H3 24/32, H4 20/28, Body Lg 16/24,
        # Body 14/20, Body Sm 12/20. The tracker has 18 sizes; each snaps to its nearest
        # step. Anything already on the scale (12/14/16/24) is left alone.
        "sizes": {
            "font-size:62px": "font-size:32px",     # hero (marketing only, but map anyway)
            "font-size:30px": "font-size:28px",
            "font-size:27px": "font-size:28px",
            "font-size:26px": "font-size:28px",
            "font-size:22px": "font-size:24px",
            "font-size:19px": "font-size:20px",
            "font-size:10px": "font-size:12px",
            "font-size:15.5px": "font-size:16px",
            "font-size:15px": "font-size:16px",
            "font-size:13.5px": "font-size:14px",
            "font-size:13px": "font-size:14px",
            "font-size:12.5px": "font-size:12px",
            "font-size:11.5px": "font-size:12px",
            "font-size:11px": "font-size:12px",
            "font-size:10.5px": "font-size:12px",
            "font-size:9.5px": "font-size:12px",
        },
        "buttons": {
            # Radius travels with the fill: Flo Kit puts standard buttons at 6px and reserves
            # 8px for large ones, and these are 36px-tall standard buttons.
            "border-radius:8px;background:#1E0A16": "border-radius:6px;background:#0174BE",
            "border-radius:8px;background:#261025": "border-radius:6px;background:#0174BE",
            "background:#1E0A16": "background:#0174BE",   # any without a radius alongside
            "background:#261025": "background:#0174BE",
            "background:#3E0C2D": "background:#0167A9",   # primary hover
        },
        "css": None,              # filled from inter-latin.css at build time
    },
)
# Optional. Drop a 1200x630 PNG at site/og-image.png and the link-preview tags below start
# including it, and the Twitter card upgrades from a small thumbnail to a full-width one.
# Absent, the tags are simply omitted -- never emitted pointing at a file that isn't there,
# which would break the unfurl outright.
OG_IMAGE_FILE = "og-image.png"


def png_size(path):
    """(width, height) from a PNG's IHDR, or None. Avoids a Pillow dependency in CI."""
    try:
        head = path.open("rb").read(24)
    except OSError:
        return None
    if head[:8] != b"\x89PNG\r\n\x1a\n" or head[12:16] != b"IHDR":
        return None
    return struct.unpack(">II", head[16:24])


def og_image_tags(site_dir, title):
    img = site_dir / OG_IMAGE_FILE
    size = png_size(img)
    if size is None:
        # No image: a plain summary card, title and description only.
        return '<meta name="twitter:card" content="summary">\n'
    width, height = size
    return (
        f'<meta property="og:image" content="{SITE}/{OG_IMAGE_FILE}">\n'
        f'<meta property="og:image:type" content="image/png">\n'
        f'<meta property="og:image:width" content="{width}">\n'
        f'<meta property="og:image:height" content="{height}">\n'
        f'<meta property="og:image:alt" content="{title}">\n'
        f'<meta name="twitter:card" content="summary_large_image">\n'
        f'<meta name="twitter:image" content="{SITE}/{OG_IMAGE_FILE}">\n'
    )

# NB: deliberately no <!doctype html>. Adding one flips the document from quirks mode to
# standards mode, which shifts the existing layout (page height +10px, some elements ~4px).
# Metadata parsing doesn't depend on a doctype, so the tags below work without it. Adding
# the doctype is a separate change that needs a visual review of its own.
HEAD_TEMPLATE = """<meta charset="utf-8">
<title>{TITLE}</title>
<meta name="description" content="{DESCRIPTION}">
{ROBOTS}<link rel="canonical" href="{CANONICAL}">
<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png">
<link rel="icon" type="image/png" sizes="192x192" href="/favicon-192.png">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Flo Forward">
<meta property="og:title" content="{TITLE}">
<meta property="og:description" content="{DESCRIPTION}">
<meta property="og:url" content="{CANONICAL}">
{og_image_tags}<meta name="twitter:title" content="{TITLE}">
<meta name="twitter:description" content="{DESCRIPTION}">
"""


def retheme(body, palette, fonts, buttons, sizes, contexts=None):
    """Recolour and re-font the app variant.

    The tracker sets colour in 554 inline style= attributes, which beat any stylesheet, so
    this is a build-time substitution rather than a CSS override -- no !important, no
    selectors to invent, and no runtime cost. Scoped to style= attributes on purpose: chart
    series colours live in SVG attributes and JS, and must keep their meaning.
    """
    swapped = {"colour": 0, "font": 0}

    # Buttons first, and property-anchored. A flat hex map can't tell a colour used as a
    # button fill from the same colour used as heading text -- the tracker's dark maroon is
    # both. These are Flo Kit *action* tokens (primary #0174BE, primary-hover #0167A9), not
    # the neutral text tokens the palette would otherwise assign.
    # Context rules: literal substrings that pin a colour to one *role* before the flat hex map
    # gets a chance to collapse both roles onto one token. Runs first, so rules are written
    # against the template exactly as authored -- not against whatever the size pass left behind.
    for rule in (contexts or []):
        body, n = re.subn(re.escape(rule["find"]), lambda _m, t=rule["to"]: t, body)
        swapped["context"] = swapped.get("context", 0) + n

    for src, dst in (sizes or {}).items():
        px = src.split(":")[1]
        body, n = re.subn(r'font-size:\s*' + re.escape(px), dst, body)
        swapped["size"] = swapped.get("size", 0) + n

    for src, dst in (buttons or {}).items():
        body, n = re.subn(re.escape(src), dst, body)
        swapped["button"] = swapped.get("button", 0) + n

    # The palette is an explicit allowlist of the tracker's warm neutrals, so it can be applied
    # to the whole body rather than scoped to style attributes: chart series colours, status
    # pill colours and warning tints simply aren't in it and can never match. That coverage
    # matters -- colours reach the DOM through style=, style-hover=, <style> blocks, SVG
    # fill=/stroke= attributes and JS chart config, and scoping to any one of those left the
    # others warm.
    #
    # #192B92 is the one hex the flat map cannot handle: the tracker uses it both as a UI accent
    # (active tab, stat numerals, section headings -- inline style=) and as a chart series
    # colour (sparkline stroke and dots, donut, bar fill, legend swatch -- quoted in JS and in
    # SVG attributes). The palette sends it to primary/50 for the UI, which is correct there and
    # wrong for a data series: it would make chart lines the same blue as buttons and links. The
    # context rules above run first and peel the chart uses off to the info ramp, so by the time
    # the flat pass runs only the UI occurrences are left.
    for src, dst in palette.items():
        body, n = re.subn(re.escape(src), dst, body, flags=re.I)
        swapped["colour"] += n
    # Drop the marketing faces BEFORE renaming. Renaming first would relabel these
    # @font-face blocks as 'Inter' while they still point at the Zalando Sans / SeasonMix
    # base64 payloads -- the page then renders the old faces under the new name, and the real
    # Inter is outranked and never loads. Removing them also drops their payloads from the
    # app build entirely.
    body, dropped = re.subn(r'@font-face\{[^{}]*?(?:Zalando Sans|SeasonMix)[^{}]*?\}', '', body)
    swapped["faces_dropped"] = dropped

    for src, dst in fonts.items():
        body, n = re.subn(re.escape(src), dst, body)
        swapped["font"] += n
    # SVG font-family attributes are unquoted-in-CSS terms; catch the bare form too.
    for bare in ("Zalando Sans", "SeasonMix"):
        body, n = re.subn(re.escape(bare), "Inter", body)
        swapped["font"] += n
    return body, swapped


def extract_body(dc_text: str) -> str:
    lines = dc_text.split("\n")
    start = next(i for i, l in enumerate(lines) if l.strip() == "<x-dc>")
    end_body = next(i for i, l in enumerate(lines) if l.strip() == "</body>")
    end_script = max(i for i in range(start, end_body) if lines[i].strip() == "</script>")
    body = "\n".join(l for l in lines[start:end_script + 1] if "_ds/flokit" not in l)
    assert body.startswith("<x-dc>") and body.rstrip().endswith("</script>"), "body bounds"
    return body


# Every chart legend is a set of series that must stay visually distinct. The retheme maps
# colours by hex, which has no idea two of them sit in the same legend -- mapping #4D8EFF and
# #192B92 onto one ramp step once rendered "Class of 2026" and "Class of 2028" identical, and
# nothing caught it but a screenshot. This asserts the property directly on the built body.
SERIES_SETS = (
    # (description, pattern, how many the template is known to contain)
    ("year/class series map", re.compile(r"\{ *'(?:\d{4}-\d{4}|Class of \d{4})':.{0,240}?\};"), 2),
    ("lineChart() call", re.compile(r"lineChart\(\[\{.{0,300}?\}\]"), 3),
)
SERIES_COLOUR = re.compile(r"'(#[0-9A-Fa-f]{6})'")


def check_series_distinct(body, name):
    """Fail the build if any one chart draws two series in the same colour."""
    for label, pattern, expected in SERIES_SETS:
        found = pattern.findall(body)
        # A regex that silently stops matching would make this check pass by doing nothing,
        # which is the failure mode this guard exists to prevent. Pin the count.
        assert len(found) == expected, (
            "[%s] %s: matched %d, expected %d -- the markup moved, so this check is no longer "
            "looking at the charts. Fix the pattern, do not lower the number."
            % (name, label, len(found), expected))
        for chunk in found:
            colours = [c.upper() for c in SERIES_COLOUR.findall(chunk)]
            if len(colours) < 2:
                continue
            dupes = {c for c in colours if colours.count(c) > 1}
            assert not dupes, (
                "[%s] %s draws two series in %s -- they will be indistinguishable in the legend.\n"
                "   %s\n   Give one of them a different step in app-palette.json."
                % (name, label, ", ".join(sorted(dupes)), chunk[:200]))


def build_variant(template_text, shell_text, variant):
    """Write one variant's page. Same template and data for every variant; only the injected
    VARIANT config, the head metadata and the trailing CSS differ."""
    config = json.dumps({"name": variant["name"], "routeBase": variant["route_base"]})
    dc_text = template_text.replace(VARIANT_MARKER, config)
    assert config in dc_text, "VARIANT injection marker missing/duplicated"

    body = extract_body(dc_text)
    if variant.get("retheme"):
        palette_doc = json.loads(PALETTE_JSON.read_text(encoding="utf-8"))
        palette = palette_doc["map"]
        fonts = {"'SeasonMix'": "'Inter'", "'Zalando Sans'": "'Inter'"}
        body, swapped = retheme(body, palette, fonts, variant.get("buttons"),
                                variant.get("sizes"), palette_doc.get("context"))
        print("  [%s] retheme: %d colour, %d button, %d size, %d font swaps, %d context, %d @font-face dropped"
              % (variant["name"], swapped["colour"], swapped.get("button", 0), swapped.get("size", 0), swapped["font"],
                 swapped.get("context", 0), swapped.get("faces_dropped", 0)))
    check_series_distinct(body, variant["name"])
    enc = json.dumps(body).replace("</script", "<\\/script").replace("<!--", "<\\!--")

    i = shell_text.find("window.__DC_SRC__=")
    s0 = i + len("window.__DC_SRC__=")
    j = shell_text.find('";</script>', s0)
    assert i >= 0 and j > s0, "__DC_SRC__ slot not found in shell"
    shell = shell_text[:s0] + enc + shell_text[j + 1:]

    robots = f'<meta name="robots" content="{variant["robots"]}">\n' if variant["robots"] else ""
    head = HEAD_TEMPLATE.format(
        TITLE=variant["title"], DESCRIPTION=DESCRIPTION, CANONICAL=CANONICAL, ROBOTS=robots,
        og_image_tags=og_image_tags(SITE_DIR, variant["title"]),
    )
    variant_css = variant["css"]
    if variant_css is None:      # the app variant needs Inter inlined; the page loads no
        variant_css = INTER_CSS.read_text(encoding="utf-8")   # external fonts by design
        # Flo Kit: "Inter with tabular-nums carries table values and token chips." Nothing
        # inline sets font-variant-numeric, so this applies without a specificity fight.
        variant_css += "\ntable td, table th { font-variant-numeric: tabular-nums; }\n"
    css = "\n<style>%s</style>\n" % variant_css if variant_css else ""

    out = SITE_DIR.joinpath(*variant["out"])
    out.parent.mkdir(parents=True, exist_ok=True)
    page = head + shell + body + css
    out.write_text(page, encoding="utf-8")
    print(f"built {out} [{variant['name']}] ({len(page):,} bytes; body {len(body):,})")


def build() -> None:
    template_text = TEMPLATE.read_text(encoding="utf-8")
    data_json = DATA_JSON.read_text(encoding="utf-8").strip()
    json.loads(data_json)  # validate it parses
    assert template_text.count(DATA_MARKER) == 1, "DATA injection marker missing/duplicated"
    assert template_text.count(VARIANT_MARKER) == 1, "VARIANT injection marker missing/duplicated"
    template_text = template_text.replace(DATA_MARKER, data_json)
    shell_text = SHELL.read_text(encoding="utf-8")
    for variant in VARIANTS:
        build_variant(template_text, shell_text, variant)


if __name__ == "__main__":
    build()
