#!/usr/bin/env python3
"""Build site/tracker/index.html from the template + data.json.

Inputs (all in this pipeline/ dir):
  template.dc.html     - the app (contains the `const DATA = /* __DATA_INJECT__ */{}/* __DATA_INJECT__ */;` marker)
  data.json            - the dashboard's values (regenerated by generate.py)
  artifact-shell.html  - stable inlined React + ReactDOM + support.js + the __DC_SRC__ slot (rarely changes)

Output:
  ../site/tracker/index.html  (Vercel serves this at /tracker)

The written page is HEAD (title/icons/link-preview tags, defined below) + shell + body.

The artifact carries the app body twice: as the escaped __DC_SRC__ payload AND as the
raw inline <x-dc> body that support.js actually renders. This build writes BOTH from the
current template+data (a stale inline body ships a broken page).

Usage:  python3 build.py
"""
import json, pathlib, re, struct

PIPE = pathlib.Path(__file__).parent
TEMPLATE = PIPE / "template.dc.html"
DATA_JSON = PIPE / "data.json"
SHELL = PIPE / "artifact-shell.html"
PALETTE_JSON = PIPE / "app-palette.json"
INTER_CSS = PIPE / "inter-latin.css"
SITE_DIR = PIPE.parent / "site"

DATA_MARKER = "/* __DATA_INJECT__ */{}/* __DATA_INJECT__ */"
VARIANT_MARKER = "/* __VARIANT_INJECT__ */{ name: 'web', routeBase: '/tracker' }/* __VARIANT_INJECT__ */"

# Document head. The shell starts straight at <script>, so without this the page ships no
# title, no icon, no charset and no link-preview tags. It lives here rather than in
# artifact-shell.html (which is regenerated wholesale) or the template's <helmet> block --
# helmet is appended by JS after boot, which browsers honour but crawlers and link unfurlers
# never see. HTML5 implies <head> for leading meta/title, so no wrapper tags are needed.
DESCRIPTION = (
    "Market updates and trends across entry-level and lateral attorney recruiting, updated "
    "every weekday. Now supporting both law firm and public interest recruiting insights."
)
SITE = "https://resources.joinflo.com"
# The public page is canonical for both builds: every /tracker/* path is served the same
# document by the vercel.json rewrite, and the in-app copy is that content again -- without
# this, crawlers would treat each deep link and the whole app variant as duplicates.
CANONICAL = f"{SITE}/tracker"

# One template, two builds. 'web' is the public marketing page; 'app' is the pared-back copy
# for users arriving from inside the Flo application. Never fork template.dc.html -- put
# differences behind VARIANT there, so both stay in step including on the daily refresh.
VARIANTS = (
    {
        "name": "web",
        "out": ("tracker", "index.html"),
        "route_base": "/tracker",
        "title": "Legal Recruiting Tracker | Flo Forward",
        "robots": None,
        "retheme": False,
        # Per-variant CSS, appended after the body so it wins over the runtime's own styles.
        "css": "",
    },
    {
        "name": "app",
        "out": ("app", "tracker", "index.html"),
        "route_base": "/app/tracker",
        "title": "Legal Recruiting Tracker",
        # Same content as the public page: keep it out of search, point search at that one.
        "robots": "noindex, nofollow",
        "retheme": True,          # apply app-palette.json + Inter to inline styles
        "css": None,              # filled from inter-latin.css at build time
    },
)
# Optional. Drop a 1200x630 PNG at site/og-image.png and the link-preview tags below start
# including it, and the Twitter card upgrades from a small thumbnail to a full-width one.
# Absent, the tags are simply omitted -- never emitted pointing at a file that isn't there,
# which would break the unfurl outright.
OG_IMAGE_FILE = "og-image.png"


def png_size(path):
    """(width, height) from a PNG's IHDR, or None. Avoids a Pillow dependency in CI."""
    try:
        head = path.open("rb").read(24)
    except OSError:
        return None
    if head[:8] != b"\x89PNG\r\n\x1a\n" or head[12:16] != b"IHDR":
        return None
    return struct.unpack(">II", head[16:24])


def og_image_tags(site_dir, title):
    img = site_dir / OG_IMAGE_FILE
    size = png_size(img)
    if size is None:
        # No image: a plain summary card, title and description only.
        return '<meta name="twitter:card" content="summary">\n'
    width, height = size
    return (
        f'<meta property="og:image" content="{SITE}/{OG_IMAGE_FILE}">\n'
        f'<meta property="og:image:type" content="image/png">\n'
        f'<meta property="og:image:width" content="{width}">\n'
        f'<meta property="og:image:height" content="{height}">\n'
        f'<meta property="og:image:alt" content="{title}">\n'
        f'<meta name="twitter:card" content="summary_large_image">\n'
        f'<meta name="twitter:image" content="{SITE}/{OG_IMAGE_FILE}">\n'
    )

# NB: deliberately no <!doctype html>. Adding one flips the document from quirks mode to
# standards mode, which shifts the existing layout (page height +10px, some elements ~4px).
# Metadata parsing doesn't depend on a doctype, so the tags below work without it. Adding
# the doctype is a separate change that needs a visual review of its own.
HEAD_TEMPLATE = """<meta charset="utf-8">
<title>{TITLE}</title>
<meta name="description" content="{DESCRIPTION}">
{ROBOTS}<link rel="canonical" href="{CANONICAL}">
<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png">
<link rel="icon" type="image/png" sizes="192x192" href="/favicon-192.png">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Flo Forward">
<meta property="og:title" content="{TITLE}">
<meta property="og:description" content="{DESCRIPTION}">
<meta property="og:url" content="{CANONICAL}">
{og_image_tags}<meta name="twitter:title" content="{TITLE}">
<meta name="twitter:description" content="{DESCRIPTION}">
"""


def retheme(body, palette, fonts):
    """Recolour and re-font the app variant.

    The tracker sets colour in 554 inline style= attributes, which beat any stylesheet, so
    this is a build-time substitution rather than a CSS override -- no !important, no
    selectors to invent, and no runtime cost. Scoped to style= attributes on purpose: chart
    series colours live in SVG attributes and JS, and must keep their meaning.
    """
    swapped = {"colour": 0, "font": 0}

    # The palette is an explicit allowlist of the tracker's warm neutrals, so it can be applied
    # to the whole body rather than scoped to style attributes: chart series colours, status
    # pill colours and warning tints simply aren't in it and can never match. That coverage
    # matters -- colours reach the DOM through style=, style-hover=, <style> blocks, SVG
    # fill=/stroke= attributes and JS chart config, and scoping to any one of those left the
    # others warm.
    #
    # One deliberate exception to "series colours are untouched": #192B92 is both a stat-number
    # colour and a chart series colour, so mapping it moves that series to the product's own
    # strong blue (#013B5D). It stays distinct from the other series.
    for src, dst in palette.items():
        body, n = re.subn(re.escape(src), dst, body, flags=re.I)
        swapped["colour"] += n
    for src, dst in fonts.items():
        body, n = re.subn(re.escape(src), dst, body)
        swapped["font"] += n
    # SVG font-family attributes are unquoted-in-CSS terms; catch the bare form too.
    for bare in ("Zalando Sans", "SeasonMix"):
        body, n = re.subn(re.escape(bare), "Inter", body)
        swapped["font"] += n
    return body, swapped


def extract_body(dc_text: str) -> str:
    lines = dc_text.split("\n")
    start = next(i for i, l in enumerate(lines) if l.strip() == "<x-dc>")
    end_body = next(i for i, l in enumerate(lines) if l.strip() == "</body>")
    end_script = max(i for i in range(start, end_body) if lines[i].strip() == "</script>")
    body = "\n".join(l for l in lines[start:end_script + 1] if "_ds/flokit" not in l)
    assert body.startswith("<x-dc>") and body.rstrip().endswith("</script>"), "body bounds"
    return body


def build_variant(template_text, shell_text, variant):
    """Write one variant's page. Same template and data for every variant; only the injected
    VARIANT config, the head metadata and the trailing CSS differ."""
    config = json.dumps({"name": variant["name"], "routeBase": variant["route_base"]})
    dc_text = template_text.replace(VARIANT_MARKER, config)
    assert config in dc_text, "VARIANT injection marker missing/duplicated"

    body = extract_body(dc_text)
    if variant.get("retheme"):
        palette = json.loads(PALETTE_JSON.read_text(encoding="utf-8"))["map"]
        fonts = {"'SeasonMix'": "'Inter'", "'Zalando Sans'": "'Inter'"}
        body, swapped = retheme(body, palette, fonts)
        print("  [%s] retheme: %d colour swaps, %d font swaps"
              % (variant["name"], swapped["colour"], swapped["font"]))
    enc = json.dumps(body).replace("</script", "<\\/script").replace("<!--", "<\\!--")

    i = shell_text.find("window.__DC_SRC__=")
    s0 = i + len("window.__DC_SRC__=")
    j = shell_text.find('";</script>', s0)
    assert i >= 0 and j > s0, "__DC_SRC__ slot not found in shell"
    shell = shell_text[:s0] + enc + shell_text[j + 1:]

    robots = f'<meta name="robots" content="{variant["robots"]}">\n' if variant["robots"] else ""
    head = HEAD_TEMPLATE.format(
        TITLE=variant["title"], DESCRIPTION=DESCRIPTION, CANONICAL=CANONICAL, ROBOTS=robots,
        og_image_tags=og_image_tags(SITE_DIR, variant["title"]),
    )
    variant_css = variant["css"]
    if variant_css is None:      # the app variant needs Inter inlined; the page loads no
        variant_css = INTER_CSS.read_text(encoding="utf-8")   # external fonts by design
    css = "\n<style>%s</style>\n" % variant_css if variant_css else ""

    out = SITE_DIR.joinpath(*variant["out"])
    out.parent.mkdir(parents=True, exist_ok=True)
    page = head + shell + body + css
    out.write_text(page, encoding="utf-8")
    print(f"built {out} [{variant['name']}] ({len(page):,} bytes; body {len(body):,})")


def build() -> None:
    template_text = TEMPLATE.read_text(encoding="utf-8")
    data_json = DATA_JSON.read_text(encoding="utf-8").strip()
    json.loads(data_json)  # validate it parses
    assert template_text.count(DATA_MARKER) == 1, "DATA injection marker missing/duplicated"
    assert template_text.count(VARIANT_MARKER) == 1, "VARIANT injection marker missing/duplicated"
    template_text = template_text.replace(DATA_MARKER, data_json)
    shell_text = SHELL.read_text(encoding="utf-8")
    for variant in VARIANTS:
        build_variant(template_text, shell_text, variant)


if __name__ == "__main__":
    build()
