#!/usr/bin/env python3
"""Build site/tracker/index.html from the template + data.json.

Inputs (all in this pipeline/ dir):
  template.dc.html     - the app (contains the `const DATA = /* __DATA_INJECT__ */{}/* __DATA_INJECT__ */;` marker)
  data.json            - the dashboard's values (regenerated by generate.py)
  artifact-shell.html  - stable inlined React + ReactDOM + support.js + the __DC_SRC__ slot (rarely changes)

Output:
  ../site/tracker/index.html  (Vercel serves this at /tracker)

The written page is HEAD (title/icons/link-preview tags, defined below) + shell + body.

The artifact carries the app body twice: as the escaped __DC_SRC__ payload AND as the
raw inline <x-dc> body that support.js actually renders. This build writes BOTH from the
current template+data (a stale inline body ships a broken page).

Usage:  python3 build.py
"""
import json, pathlib

PIPE = pathlib.Path(__file__).parent
TEMPLATE = PIPE / "template.dc.html"
DATA_JSON = PIPE / "data.json"
SHELL = PIPE / "artifact-shell.html"
OUT = PIPE.parent / "site" / "tracker" / "index.html"

DATA_MARKER = "/* __DATA_INJECT__ */{}/* __DATA_INJECT__ */"

# Document head. The shell starts straight at <script>, so without this the page ships no
# title, no icon, no charset and no link-preview tags. It lives here rather than in
# artifact-shell.html (which is regenerated wholesale) or the template's <helmet> block --
# helmet is appended by JS after boot, which browsers honour but crawlers and link unfurlers
# never see. HTML5 implies <head> for leading meta/title, so no wrapper tags are needed.
TITLE = "Legal Recruiting Tracker | Flo Forward"
DESCRIPTION = (
    "Market updates and trends across entry-level and lateral attorney recruiting, updated "
    "every weekday. Now supporting both law firm and public interest recruiting insights."
)
# Every /tracker/* path is served this same document by the vercel.json rewrite, so they are
# all one canonical page -- without this, crawlers would treat each deep link as a duplicate.
CANONICAL = "https://resources.joinflo.com/tracker"

# NB: deliberately no <!doctype html>. Adding one flips the document from quirks mode to
# standards mode, which shifts the existing layout (page height +10px, some elements ~4px).
# Metadata parsing doesn't depend on a doctype, so the tags below work without it. Adding
# the doctype is a separate change that needs a visual review of its own.
HEAD = f"""<meta charset="utf-8">
<title>{TITLE}</title>
<meta name="description" content="{DESCRIPTION}">
<link rel="canonical" href="{CANONICAL}">
<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png">
<link rel="icon" type="image/png" sizes="192x192" href="/favicon-192.png">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Flo Forward">
<meta property="og:title" content="{TITLE}">
<meta property="og:description" content="{DESCRIPTION}">
<meta property="og:url" content="{CANONICAL}">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="{TITLE}">
<meta name="twitter:description" content="{DESCRIPTION}">
"""


def extract_body(dc_text: str) -> str:
    lines = dc_text.split("\n")
    start = next(i for i, l in enumerate(lines) if l.strip() == "<x-dc>")
    end_body = next(i for i, l in enumerate(lines) if l.strip() == "</body>")
    end_script = max(i for i in range(start, end_body) if lines[i].strip() == "</script>")
    body = "\n".join(l for l in lines[start:end_script + 1] if "_ds/flokit" not in l)
    assert body.startswith("<x-dc>") and body.rstrip().endswith("</script>"), "body bounds"
    return body


def build() -> None:
    dc_text = TEMPLATE.read_text(encoding="utf-8")
    data_json = DATA_JSON.read_text(encoding="utf-8").strip()
    json.loads(data_json)  # validate it parses
    assert dc_text.count(DATA_MARKER) == 1, "DATA injection marker missing/duplicated"
    dc_text = dc_text.replace(DATA_MARKER, data_json)

    body = extract_body(dc_text)
    enc = json.dumps(body).replace("</script", "<\\/script").replace("<!--", "<\\!--")

    shell = SHELL.read_text(encoding="utf-8")
    i = shell.find("window.__DC_SRC__=")
    s0 = i + len("window.__DC_SRC__=")
    j = shell.find('";</script>', s0)
    assert i >= 0 and j > s0, "__DC_SRC__ slot not found in shell"
    shell = shell[:s0] + enc + shell[j + 1:]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    page = HEAD + shell + body
    OUT.write_text(page, encoding="utf-8")
    print(f"built {OUT} ({len(page):,} bytes; body {len(body):,})")


if __name__ == "__main__":
    build()
